<a href="https://colab.research.google.com/github/IrfanPavel/Churn_Modeling/blob/main/Churn_Modeling%20using%20ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.7.0'

In [5]:
dataset=pd.read_csv("/content/Churn_Modelling.csv")

In [10]:
dataset

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [8]:
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [9]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
y

array([1, 0, 1, ..., 1, 1, 0])

# **Encoding Categorical Data**

# Label Encoding The "Gender" Column

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [13]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

# One Hot Encoding The "Geography" Column

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
X=np.array(ct.fit_transform(X))

In [15]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

# Splitting the dataset into the training and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

# **Feature Scaling**

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# **Building The ANN
# Initializing the ANN** 

In [19]:
ann=tf.keras.models.Sequential()

# **Adding The Input layer and The First Hidden Layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

# **Adding The Input layer and The Second Hidden Layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

# **Adding The Output Layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

# **Training The ANN **

In [21]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

# Training The ANN ON The Traing set

In [22]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 3.6138 - accuracy: 0.2260
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 3.6138 - accuracy: 0.2260
Epoch 3/100
250/250 [==============================] - 0s 990us/step - loss: 3.6138 - accuracy: 0.2260
Epoch 4/100
250/250 [==============================] - 0s 991us/step - loss: 3.6138 - accuracy: 0.2260
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 3.6138 - accuracy: 0.2260
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 3.6138 - accuracy: 0.2260
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 3.6138 - accuracy: 0.2260
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 3.6138 - accuracy: 0.2260
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 3.6138 - accuracy: 0.2260
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 3.6138 - ac

In [34]:
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

# Predicting The Test Set Results

In [ ]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
# print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

In [36]:
y_pred

array([[False,  True, False, ...,  True,  True,  True],
       [ True, False, False, ...,  True, False, False],
       [False, False,  True, ...,  True,  True, False],
       ...,
       [False, False,  True, ...,  True, False,  True],
       [False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True, False,  True]])

# **Confusion Matrix**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)